name: Lab 1 Grading

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Build and Start
        run: docker compose up -d

      - name: Wait for Readiness
        run: |
          for i in {1..15}; do
            if curl -s localhost:8080/health; then
              echo "App is ready!"
              break
            fi
            echo "Waiting..."
            sleep 3
          done

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab1_test.sh
          ./tests/lab1_test.sh
